/* ======= STYLES COLOR ======= */
export const RED = 'portfolio.red'
export const BLUE = 'portfolio.blue'
export const LIGHT_RED = 'portfolio.lightRed'
export const DARK_RED = 'portfolio.darkRed'
export const LIGHT_BLUE = 'portfolio.lightBlue'
export const DARK_BLUE = 'portfolio.darkBlue'
export const BLACK = 'portfolio.black'
export const WHITE = 'portfolio.white'
export const GRAY = 'portfolio.gray'
